### ISSUE TITLE
Compiling qml-go with go 1.12.1 produces errors

### ISSUE THREAD

**Issue by arubislander** [nanu-c/qml-go#2]
When compiling qml-go with go 1.12.1 the following errors are thrown:
```
github.com/nanu-c/qml-go/cdata.Ref: relocation target runtime.acquirem not defined for ABI0 (but is defined for ABIInternal)
github.com/nanu-c/qml-go/cdata.Ref: relocation target runtime.releasem not defined for ABI0 (but is defined for ABIInternal)
```

I did find [this reference](https://github.com/go-qml/qml/issues/190), but I do not understand the workaround.

**Comment by nanu-c** [comment]
fixed in 846042127ff96e69a15a5bc3a741b5ab828ef1d5
:) Yeai
